version: '3'
services:
  llmgen-eval:
    build: .
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./eval
        target: /usr/pipeline/eval
      - type: bind
        source: ./generator
        target: /usr/pipeline/generator

